apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rate-pulse-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.rate-pulse.me
      secretName: rate-pulse-tls
  rules:
    - host: api.rate-pulse.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rate-pulse-api-service
                port:
                  number: 80