apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rate-pulse-ingress
  annotations:
    # Optional: if you want TLS later, Traefik handles it
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: "*.rate-pulse.me"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rate-pulse-api-service
                port:
                  number: 80