apiVersion: v1
kind: Service
metadata:
  name: rate-pulse-api-service
spec:
  selector:
    app: rate-pulse-api  # This MUST match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP