name: Deploy to production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: vinhtongthanh57/rate-pulse
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Build & push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy on Droplet
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Copy Kubernetes manifests
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          password: ${{ secrets.DROPLET_PASSWORD || secrets.PASSWORD }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "digitalocean/deployment.yaml, digitalocean/service.yaml"
          target: "~/rate-pulse"

      - name: SSH â†’ Apply Secrets & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          password: ${{ secrets.DROPLET_PASSWORD || secrets.PASSWORD }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # 1. Update/Create the Secret using GitHub Secrets
            kubectl create secret generic rate-pulse-secrets \
              --from-literal=DB_SOURCE='${{ secrets.DB_SOURCE }}' \
              --from-literal=DB_DRIVER='postgres' \
              --from-literal=SERVER_ADDRESS='${{ secrets.SERVER_ADDRESS }}' \
              --from-literal=ACCESS_TOKEN_DURATION='${{ secrets.ACCESS_TOKEN_DURATION }}' \
              --from-literal=TOKEN_SYMMETRIC_KEY='${{ secrets.TOKEN_SYMMETRIC_KEY }}' \
              --dry-run=client -o yaml | kubectl apply -f -

            # 2. Apply the Kubernetes Blueprints
            kubectl apply -f ~/rate-pulse/digitalocean/deployment.yaml
            kubectl apply -f ~/rate-pulse/digitalocean/service.yaml

            # 3. Force a restart to ensure the latest image is pulled
            kubectl rollout restart deployment/rate-pulse-api-deployment
