name: Deploy to production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: vinhtongthanh57/rate-pulse
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Build & push (docker compose)
        run: |
          export IMAGE_TAG=${IMAGE_TAG}
          docker compose build
          docker compose push

  deploy:
    name: Deploy on Droplet
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Copy docker-compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          password: ${{ secrets.DROPLET_PASSWORD || secrets.PASSWORD }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "~/"

      - name: SSH â†’ pull & run
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          password: ${{ secrets.DROPLET_PASSWORD || secrets.PASSWORD }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            export IMAGE_TAG=${{ github.sha }}
            docker compose pull
            docker compose up -d